spring.application.name=ats-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/ats_db
spring.datasource.username=postgres
spring.datasource.password=Swagat@2004
spring.jpa.hibernate.ddl-auto=update